published:
  - app:
      category: life
      application: weather
      name: 天气
      publish_date: 2019-09-15
      url: /service/weather
      desc: this is a weather app.
  - app:
      category: life
      application: backup
      name: 图片备份
      publish_date: 2019-09-15
      url: /service/image
      desc: this is a backup app.
  - app:
      category: life
      application: stock
      name: 股票
      publish_date: 2019-09-16
      url: /service/stock
      desc: this is a stock app.
  - app:
      category: life
      application: constellation
      name: 星座
      publish_date: 2019-09-16
      url: /service/constellation
      desc: this is a constellation app.
  - app:
      category: life
      application: joke
      name: 笑话
      publish_date: 2019-09-16
      url: /service/joke
      desc: this is a joke app.

developing:
  - app: