# Generated by Django 2.0 on 2019-09-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190916_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='focus_stock',
            new_name='focus_stocks',
        ),
    ]
