# Generated by Django 2.0 on 2019-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('authorization', '0006_auto_20190924_1718'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authorizati_nicknam_b76290_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='apis.App'),
        ),
    ]
